### ISSUE TITLE
Can't check the box in User Preferences (1.1.5 and 1.1.6)

### ISSUE THREAD

**Issue by Frostie2** [agoose77/bge_network_addon#25]
Can't check the box in User Preferences. I'm getting a lot of errors

**Comment by rafcolson** [comment]
Same here.
```python
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\Raf\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bge_network_addon\__init__.py", line 44, in <module>
    from network.replicable import Replicable
ImportError: No module named 'network'
```

**Comment by Ganymede20** [comment]
I got same error. Please fix it.
